# Generated by Django 5.0.3 on 2024-05-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadeestocagem',
            options={'ordering': ['sigla'], 'verbose_name': 'Unidade de estocagem', 'verbose_name_plural': 'Unidades de estocagem'},
        ),
    ]
