# Generated by Django 5.0.3 on 2024-05-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alter_unidadeestocagem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadesfab',
            name='foto',
            field=models.CharField(help_text='Foto da Organização militar', max_length=3, verbose_name='Sigla da unidade'),
        ),
    ]
