# Generated by Django 5.0.3 on 2024-05-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_unidadesfab_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadesfab',
            name='foto',
            field=models.ImageField(help_text='Foto da Organização militar', upload_to='fotos_unidades/', verbose_name='Sigla da unidade'),
        ),
    ]
