# Generated by Django 5.0.3 on 2024-05-29 16:48

import apps.authentication.models.perfil
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['usuario'], 'verbose_name': 'Perfil do Usuário', 'verbose_name_plural': 'Perfis dos Usuários'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to=apps.authentication.models.perfil.user_directory_path, verbose_name='Foto do Usuário'),
        ),
        migrations.AddIndex(
            model_name='perfil',
            index=models.Index(fields=['usuario'], name='authenticat_usuario_6e1471_idx'),
        ),
        migrations.AddIndex(
            model_name='perfil',
            index=models.Index(fields=['setor'], name='authenticat_setor_3a5fce_idx'),
        ),
        migrations.AddIndex(
            model_name='perfil',
            index=models.Index(fields=['foto'], name='authenticat_foto_14eaa4_idx'),
        ),
    ]
